---
_hotel_id: THE876
_portal_id: ''
latitude: 42.34482
longitude: -71.09701
name: The Verb Hotel
email: ''
phone_number: "--"
address:
  street1: 1271 Boylston St
  street2: ''
  state: Massachusetts
  city: Boston
  country: United States
  zip_code: '02215'
